### ISSUE TITLE
compilation errors with vala 0.44.4

### ISSUE THREAD

**Issue by decathorpe** [elementary/photos#509]
After upgrading vala from 0.44.3 to 0.44.4, these errors started to make the build fail:

```
dee-1.0.vapi:44.35-44.44: error: construct properties not supported for specified property type
		public Dee.Filter filter { get; construct; }
		                                ^^^^^^^^^^
dee-1.0.vapi:76.35-76.44: error: construct properties not supported for specified property type
		public Dee.ModelReader reader { construct; }
		                                ^^^^^^^^^^
```
